[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 404

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 404

# not exist
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
  force = false